### ISSUE TITLE
Call custom action

### ISSUE THREAD

**Issue by phuocle** [DigitalFlow/Xrm-WebApi-Client#6]
I call a custom action with code here
```javascript
require(["WebApiClient"], function (WebApiClient) {                    
    var request = Object.create(WebApiClient.Requests.Request.prototype, {
        method: { value: "POST" },
        name: { value: "pl_Ajax" },                        
        payload: {
            'function': "SendEmail",
            'input': Xrm.Page.data.entity.getId()
        }
    });
    WebApiClient.Execute(request)
        .then(function (response) {
            debugger;
        })
        .catch(function (error) {
            debugger;
        });
});
```

I get an error

```
Uncaught ReferenceError: WebApiClient is not defined
    at Requests.Request.buildUrl (http://....../CRM/%7B636235238420000749%7D/WebResources/pl_/lib/WebApiClient/WebApiClient.js:6263:23)
    at eval (eval at evaluate (:85:21), <anonymous>:1:9)
    at Object.WebApiClient.Execute (http://....../CRM/%7B636235238420000749%7D/WebResources/pl_/lib/WebApiClient/WebApiClient.js:6178:9)
    at <anonymous>:272:34
    at Object.execCb (<anonymous>:5:15508)
    at b.check (<anonymous>:5:8048)
    at b.enable (<anonymous>:5:11254)
    at b.init (<anonymous>:5:7002)
    at <anonymous>:5:13499
```

debug with Chrome and see that line
```javascript
return WebApiClient.SendRequest(request.method, request.buildUrl(), request.payload, request.headers);
```

the `request.buildUrl()` throw exception above

**Comment by DigitalFlow** [comment]
Just took a look at it, this is an issue in the WebApiClient.Requests implementation.

It expects to find a global WebApiClient variable to exist. This will be resolved, for the time being you can export the WebApiClient to a global variable with this name and it should work.

**Comment by DigitalFlow** [comment]
Hey @phuocle,

I just published v2.2.1, the error that you reported should be fixed with this release.
Please update and give me some feedback, whether your issues are resolved.

Kind Regards,
Florian

**Comment by phuocle** [comment]
This is the **worked** code
```javascript
var request = Object.create(WebApiClient.Requests.Request.prototype, {
    method: { value: "POST" },
    name: { value: "pl_Ajax" }
});
request.payload = {
    'function': "ExtendOneMonthTrial",
    'input': Xrm.Page.data.entity.getId()
};
WebApiClient.Execute(request)
    .then(function (response) {
        //success
    });
```

But this code **not work**. Why ?
```javascript
var request = Object.create(WebApiClient.Requests.Request.prototype, {
    method: { value: "POST" },
    name: { value: "pl_Ajax" },
    payload:  {
        'function': "ExtendOneMonthTrial",
        'input': Xrm.Page.data.entity.getId()
    };
});
WebApiClient.Execute(request) //exception because request.payload = undefine
    .then(function (response) {
        //success
    });
```

Thanks for a great ```WebApiClient ```

**Comment by DigitalFlow** [comment]
Hello @phuocle,

Sorry for the late response, I did not get a notification for your message.
Thanks for your positive feedback, it is much appreciated :)

As for your last request, when using Object.create, you need to wrap your values in a value object like so:

```JavaScript
var request = Object.create(WebApiClient.Requests.Request.prototype, { 
    method: { value: "POST" }, 
    name: { value: "pl_Ajax" }, 
    payload: { 
        value: 
        {
            'function': "ExtendOneMonthTrial", 
            'input': Xrm.Page.data.entity.getId() 
        }
    }
}); 

WebApiClient.Execute(request)
.then(function (response) { //success });
```

Or like so:

```JavaScript
var request = Object.create(WebApiClient.Requests.Request.prototype, { 
    method: { value: "POST" }, 
    name: { value: "pl_Ajax" },
}); 

WebApiClient.Execute(request.with({
    payload: {
            'function': "ExtendOneMonthTrial", 
            'input': Xrm.Page.data.entity.getId() 
        }
    }))
.then(function (response) { //success });
```
